/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  Versioned,
  VersionedInterface,
} from "../../../../../@hyperlane-xyz/core/contracts/upgrade/Versioned";

const _abi = [
  {
    inputs: [],
    name: "VERSION",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060b58061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063ffa1ad7414602d575b600080fd5b60336047565b604051603e91906066565b60405180910390f35b600381565b600060ff82169050919050565b606081604c565b82525050565b6000602082019050607960008301846059565b9291505056fea2646970667358221220549186c9aab34a8657a187a9b66aea3be0313c54b41d44f5755ae7840725893364736f6c63430008180033";

type VersionedConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: VersionedConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Versioned__factory extends ContractFactory {
  constructor(...args: VersionedConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Versioned & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Versioned__factory {
    return super.connect(runner) as Versioned__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): VersionedInterface {
    return new Interface(_abi) as VersionedInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Versioned {
    return new Contract(address, _abi, runner) as unknown as Versioned;
  }
}
