/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PrivateTransferVault {
  export type EncryptedEnvelopeStruct = {
    senderPublicKey: BytesLike;
    nonce: BytesLike;
    ciphertext: BytesLike;
  };

  export type EncryptedEnvelopeStructOutput = [
    senderPublicKey: string,
    nonce: string,
    ciphertext: string
  ] & { senderPublicKey: string; nonce: string; ciphertext: string };
}

export interface PrivateTransferVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PACKAGE_VERSION"
      | "domains"
      | "encryptedTransfers"
      | "enrollRemoteRouter"
      | "enrollRemoteRouters"
      | "handle"
      | "hook"
      | "interchainSecurityModule"
      | "localDomain"
      | "mailbox"
      | "owner"
      | "processTransfer"
      | "processedPayloads"
      | "renounceOwnership"
      | "revealTransfer"
      | "routers"
      | "setHook"
      | "setInterchainSecurityModule"
      | "transferOwnership"
      | "unenrollRemoteRouter"
      | "unenrollRemoteRouters"
      | "vaultPublicKey"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EncryptedTransferStored"
      | "HookSet"
      | "Initialized"
      | "IsmSet"
      | "OwnershipTransferred"
      | "PrivatePayloadProcessed"
      | "TransferAcknowledged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PACKAGE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "domains", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "encryptedTransfers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "enrollRemoteRouter",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "enrollRemoteRouters",
    values: [BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "handle",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "hook", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "interchainSecurityModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "localDomain",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "mailbox", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processTransfer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processedPayloads",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealTransfer",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "routers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHook",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setInterchainSecurityModule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unenrollRemoteRouter",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unenrollRemoteRouters",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultPublicKey",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "PACKAGE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "domains", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "encryptedTransfers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enrollRemoteRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enrollRemoteRouters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "handle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "interchainSecurityModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "localDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mailbox", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processedPayloads",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "routers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setHook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setInterchainSecurityModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unenrollRemoteRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unenrollRemoteRouters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultPublicKey",
    data: BytesLike
  ): Result;
}

export namespace EncryptedTransferStoredEvent {
  export type InputTuple = [
    transferId: BytesLike,
    originDomain: BigNumberish,
    originRouter: BytesLike,
    ciphertext: BytesLike
  ];
  export type OutputTuple = [
    transferId: string,
    originDomain: bigint,
    originRouter: string,
    ciphertext: string
  ];
  export interface OutputObject {
    transferId: string;
    originDomain: bigint;
    originRouter: string;
    ciphertext: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HookSetEvent {
  export type InputTuple = [_hook: AddressLike];
  export type OutputTuple = [_hook: string];
  export interface OutputObject {
    _hook: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IsmSetEvent {
  export type InputTuple = [_ism: AddressLike];
  export type OutputTuple = [_ism: string];
  export interface OutputObject {
    _ism: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivatePayloadProcessedEvent {
  export type InputTuple = [
    transferId: BytesLike,
    receiver: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    isNative: boolean
  ];
  export type OutputTuple = [
    transferId: string,
    receiver: string,
    token: string,
    amount: bigint,
    isNative: boolean
  ];
  export interface OutputObject {
    transferId: string;
    receiver: string;
    token: string;
    amount: bigint;
    isNative: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferAcknowledgedEvent {
  export type InputTuple = [
    transferId: BytesLike,
    destinationDomain: BigNumberish
  ];
  export type OutputTuple = [transferId: string, destinationDomain: bigint];
  export interface OutputObject {
    transferId: string;
    destinationDomain: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateTransferVault extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateTransferVault;
  waitForDeployment(): Promise<this>;

  interface: PrivateTransferVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PACKAGE_VERSION: TypedContractMethod<[], [string], "view">;

  domains: TypedContractMethod<[], [bigint[]], "view">;

  encryptedTransfers: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        bigint,
        string,
        PrivateTransferVault.EncryptedEnvelopeStructOutput,
        boolean
      ] & {
        originDomain: bigint;
        originRouter: string;
        envelope: PrivateTransferVault.EncryptedEnvelopeStructOutput;
        acknowledged: boolean;
      }
    ],
    "view"
  >;

  enrollRemoteRouter: TypedContractMethod<
    [_domain: BigNumberish, _router: BytesLike],
    [void],
    "nonpayable"
  >;

  enrollRemoteRouters: TypedContractMethod<
    [_domains: BigNumberish[], _addresses: BytesLike[]],
    [void],
    "nonpayable"
  >;

  handle: TypedContractMethod<
    [_origin: BigNumberish, _sender: BytesLike, _message: BytesLike],
    [void],
    "payable"
  >;

  hook: TypedContractMethod<[], [string], "view">;

  interchainSecurityModule: TypedContractMethod<[], [string], "view">;

  localDomain: TypedContractMethod<[], [bigint], "view">;

  mailbox: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  processTransfer: TypedContractMethod<
    [transferId: BytesLike],
    [void],
    "payable"
  >;

  processedPayloads: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean, string] & {
        receiver: string;
        token: string;
        amount: bigint;
        isNative: boolean;
        memo: string;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revealTransfer: TypedContractMethod<
    [transferId: BytesLike],
    [string],
    "view"
  >;

  routers: TypedContractMethod<[_domain: BigNumberish], [string], "view">;

  setHook: TypedContractMethod<[_hook: AddressLike], [void], "nonpayable">;

  setInterchainSecurityModule: TypedContractMethod<
    [_module: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unenrollRemoteRouter: TypedContractMethod<
    [_domain: BigNumberish],
    [void],
    "nonpayable"
  >;

  unenrollRemoteRouters: TypedContractMethod<
    [_domains: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  vaultPublicKey: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PACKAGE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "domains"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "encryptedTransfers"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        bigint,
        string,
        PrivateTransferVault.EncryptedEnvelopeStructOutput,
        boolean
      ] & {
        originDomain: bigint;
        originRouter: string;
        envelope: PrivateTransferVault.EncryptedEnvelopeStructOutput;
        acknowledged: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "enrollRemoteRouter"
  ): TypedContractMethod<
    [_domain: BigNumberish, _router: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enrollRemoteRouters"
  ): TypedContractMethod<
    [_domains: BigNumberish[], _addresses: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handle"
  ): TypedContractMethod<
    [_origin: BigNumberish, _sender: BytesLike, _message: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "hook"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "interchainSecurityModule"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "localDomain"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mailbox"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processTransfer"
  ): TypedContractMethod<[transferId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "processedPayloads"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, boolean, string] & {
        receiver: string;
        token: string;
        amount: bigint;
        isNative: boolean;
        memo: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revealTransfer"
  ): TypedContractMethod<[transferId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "routers"
  ): TypedContractMethod<[_domain: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "setHook"
  ): TypedContractMethod<[_hook: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setInterchainSecurityModule"
  ): TypedContractMethod<[_module: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unenrollRemoteRouter"
  ): TypedContractMethod<[_domain: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unenrollRemoteRouters"
  ): TypedContractMethod<[_domains: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vaultPublicKey"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "EncryptedTransferStored"
  ): TypedContractEvent<
    EncryptedTransferStoredEvent.InputTuple,
    EncryptedTransferStoredEvent.OutputTuple,
    EncryptedTransferStoredEvent.OutputObject
  >;
  getEvent(
    key: "HookSet"
  ): TypedContractEvent<
    HookSetEvent.InputTuple,
    HookSetEvent.OutputTuple,
    HookSetEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "IsmSet"
  ): TypedContractEvent<
    IsmSetEvent.InputTuple,
    IsmSetEvent.OutputTuple,
    IsmSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PrivatePayloadProcessed"
  ): TypedContractEvent<
    PrivatePayloadProcessedEvent.InputTuple,
    PrivatePayloadProcessedEvent.OutputTuple,
    PrivatePayloadProcessedEvent.OutputObject
  >;
  getEvent(
    key: "TransferAcknowledged"
  ): TypedContractEvent<
    TransferAcknowledgedEvent.InputTuple,
    TransferAcknowledgedEvent.OutputTuple,
    TransferAcknowledgedEvent.OutputObject
  >;

  filters: {
    "EncryptedTransferStored(bytes32,uint32,bytes32,bytes)": TypedContractEvent<
      EncryptedTransferStoredEvent.InputTuple,
      EncryptedTransferStoredEvent.OutputTuple,
      EncryptedTransferStoredEvent.OutputObject
    >;
    EncryptedTransferStored: TypedContractEvent<
      EncryptedTransferStoredEvent.InputTuple,
      EncryptedTransferStoredEvent.OutputTuple,
      EncryptedTransferStoredEvent.OutputObject
    >;

    "HookSet(address)": TypedContractEvent<
      HookSetEvent.InputTuple,
      HookSetEvent.OutputTuple,
      HookSetEvent.OutputObject
    >;
    HookSet: TypedContractEvent<
      HookSetEvent.InputTuple,
      HookSetEvent.OutputTuple,
      HookSetEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "IsmSet(address)": TypedContractEvent<
      IsmSetEvent.InputTuple,
      IsmSetEvent.OutputTuple,
      IsmSetEvent.OutputObject
    >;
    IsmSet: TypedContractEvent<
      IsmSetEvent.InputTuple,
      IsmSetEvent.OutputTuple,
      IsmSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PrivatePayloadProcessed(bytes32,address,address,uint256,bool)": TypedContractEvent<
      PrivatePayloadProcessedEvent.InputTuple,
      PrivatePayloadProcessedEvent.OutputTuple,
      PrivatePayloadProcessedEvent.OutputObject
    >;
    PrivatePayloadProcessed: TypedContractEvent<
      PrivatePayloadProcessedEvent.InputTuple,
      PrivatePayloadProcessedEvent.OutputTuple,
      PrivatePayloadProcessedEvent.OutputObject
    >;

    "TransferAcknowledged(bytes32,uint32)": TypedContractEvent<
      TransferAcknowledgedEvent.InputTuple,
      TransferAcknowledgedEvent.OutputTuple,
      TransferAcknowledgedEvent.OutputObject
    >;
    TransferAcknowledged: TypedContractEvent<
      TransferAcknowledgedEvent.InputTuple,
      TransferAcknowledgedEvent.OutputTuple,
      TransferAcknowledgedEvent.OutputObject
    >;
  };
}
