/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockMailboxInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "delivered"
      | "dispatch(uint32,bytes32,bytes,bytes,address)"
      | "dispatch(uint32,bytes32,bytes)"
      | "latestDispatchedId"
      | "localDomain"
      | "processor"
      | "processorAddress"
      | "setProcessorAddress"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DispatchCalled"): EventFragment;

  encodeFunctionData(
    functionFragment: "delivered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dispatch(uint32,bytes32,bytes,bytes,address)",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dispatch(uint32,bytes32,bytes)",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "latestDispatchedId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "localDomain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processorAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setProcessorAddress",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "delivered", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dispatch(uint32,bytes32,bytes,bytes,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dispatch(uint32,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestDispatchedId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "localDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "processor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProcessorAddress",
    data: BytesLike
  ): Result;
}

export namespace DispatchCalledEvent {
  export type InputTuple = [
    destinationDomain: BigNumberish,
    recipient: BytesLike,
    message: BytesLike
  ];
  export type OutputTuple = [
    destinationDomain: bigint,
    recipient: string,
    message: string
  ];
  export interface OutputObject {
    destinationDomain: bigint;
    recipient: string;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockMailbox extends BaseContract {
  connect(runner?: ContractRunner | null): MockMailbox;
  waitForDeployment(): Promise<this>;

  interface: MockMailboxInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  delivered: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  "dispatch(uint32,bytes32,bytes,bytes,address)": TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      arg3: BytesLike,
      arg4: AddressLike
    ],
    [string],
    "payable"
  >;

  "dispatch(uint32,bytes32,bytes)": TypedContractMethod<
    [
      _destinationDomain: BigNumberish,
      _recipientAddress: BytesLike,
      _messageBody: BytesLike
    ],
    [string],
    "payable"
  >;

  latestDispatchedId: TypedContractMethod<[], [string], "view">;

  localDomain: TypedContractMethod<[], [bigint], "view">;

  processor: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  processorAddress: TypedContractMethod<[], [string], "view">;

  setProcessorAddress: TypedContractMethod<
    [_processor: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "delivered"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "dispatch(uint32,bytes32,bytes,bytes,address)"
  ): TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      arg3: BytesLike,
      arg4: AddressLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "dispatch(uint32,bytes32,bytes)"
  ): TypedContractMethod<
    [
      _destinationDomain: BigNumberish,
      _recipientAddress: BytesLike,
      _messageBody: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "latestDispatchedId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "localDomain"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "processor"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "processorAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setProcessorAddress"
  ): TypedContractMethod<[_processor: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DispatchCalled"
  ): TypedContractEvent<
    DispatchCalledEvent.InputTuple,
    DispatchCalledEvent.OutputTuple,
    DispatchCalledEvent.OutputObject
  >;

  filters: {
    "DispatchCalled(uint32,bytes32,bytes)": TypedContractEvent<
      DispatchCalledEvent.InputTuple,
      DispatchCalledEvent.OutputTuple,
      DispatchCalledEvent.OutputObject
    >;
    DispatchCalled: TypedContractEvent<
      DispatchCalledEvent.InputTuple,
      DispatchCalledEvent.OutputTuple,
      DispatchCalledEvent.OutputObject
    >;
  };
}
