/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  PackageVersioned,
  PackageVersionedInterface,
} from "../../../../@hyperlane-xyz/core/contracts/PackageVersioned";

const _abi = [
  {
    inputs: [],
    name: "PACKAGE_VERSION",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class PackageVersioned__factory {
  static readonly abi = _abi;
  static createInterface(): PackageVersionedInterface {
    return new Interface(_abi) as PackageVersionedInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PackageVersioned {
    return new Contract(address, _abi, runner) as unknown as PackageVersioned;
  }
}
