/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  Indexed,
  IndexedInterface,
} from "../../../../../@hyperlane-xyz/core/contracts/libs/Indexed";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "deployedBlock",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a060405234801561001057600080fd5b50436080818152505060805160d161003160003960006049015260d16000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806382ea7bfe14602d575b600080fd5b60336047565b604051603e91906082565b60405180910390f35b7f000000000000000000000000000000000000000000000000000000000000000081565b6000819050919050565b607c81606b565b82525050565b6000602082019050609560008301846075565b9291505056fea26469706673582212208c641e4a33cd5d7712603a1984f5858e60d688c7788a5207555669537140e71d64736f6c63430008180033";

type IndexedConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: IndexedConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Indexed__factory extends ContractFactory {
  constructor(...args: IndexedConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Indexed & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Indexed__factory {
    return super.connect(runner) as Indexed__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): IndexedInterface {
    return new Interface(_abi) as IndexedInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Indexed {
    return new Contract(address, _abi, runner) as unknown as Indexed;
  }
}
