/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface MailboxInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PACKAGE_VERSION"
      | "VERSION"
      | "defaultHook"
      | "defaultIsm"
      | "delivered"
      | "deployedBlock"
      | "dispatch(uint32,bytes32,bytes,bytes,address)"
      | "dispatch(uint32,bytes32,bytes,bytes)"
      | "dispatch(uint32,bytes32,bytes)"
      | "initialize"
      | "latestDispatchedId"
      | "localDomain"
      | "nonce"
      | "owner"
      | "process"
      | "processedAt"
      | "processor"
      | "quoteDispatch(uint32,bytes32,bytes,bytes,address)"
      | "quoteDispatch(uint32,bytes32,bytes)"
      | "quoteDispatch(uint32,bytes32,bytes,bytes)"
      | "recipientIsm"
      | "renounceOwnership"
      | "requiredHook"
      | "setDefaultHook"
      | "setDefaultIsm"
      | "setRequiredHook"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DefaultHookSet"
      | "DefaultIsmSet"
      | "Dispatch"
      | "DispatchId"
      | "Initialized"
      | "OwnershipTransferred"
      | "Process"
      | "ProcessId"
      | "RequiredHookSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PACKAGE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "defaultHook",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultIsm",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "delivered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dispatch(uint32,bytes32,bytes,bytes,address)",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dispatch(uint32,bytes32,bytes,bytes)",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dispatch(uint32,bytes32,bytes)",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "latestDispatchedId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "localDomain",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nonce", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "process",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processedAt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteDispatch(uint32,bytes32,bytes,bytes,address)",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteDispatch(uint32,bytes32,bytes)",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteDispatch(uint32,bytes32,bytes,bytes)",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recipientIsm",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requiredHook",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultHook",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultIsm",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRequiredHook",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "PACKAGE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "defaultIsm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "delivered", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployedBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dispatch(uint32,bytes32,bytes,bytes,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dispatch(uint32,bytes32,bytes,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dispatch(uint32,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latestDispatchedId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "localDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "process", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "processor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoteDispatch(uint32,bytes32,bytes,bytes,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteDispatch(uint32,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteDispatch(uint32,bytes32,bytes,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recipientIsm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultIsm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRequiredHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DefaultHookSetEvent {
  export type InputTuple = [hook: AddressLike];
  export type OutputTuple = [hook: string];
  export interface OutputObject {
    hook: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultIsmSetEvent {
  export type InputTuple = [module: AddressLike];
  export type OutputTuple = [module: string];
  export interface OutputObject {
    module: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DispatchEvent {
  export type InputTuple = [
    sender: AddressLike,
    destination: BigNumberish,
    recipient: BytesLike,
    message: BytesLike
  ];
  export type OutputTuple = [
    sender: string,
    destination: bigint,
    recipient: string,
    message: string
  ];
  export interface OutputObject {
    sender: string;
    destination: bigint;
    recipient: string;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DispatchIdEvent {
  export type InputTuple = [messageId: BytesLike];
  export type OutputTuple = [messageId: string];
  export interface OutputObject {
    messageId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProcessEvent {
  export type InputTuple = [
    origin: BigNumberish,
    sender: BytesLike,
    recipient: AddressLike
  ];
  export type OutputTuple = [origin: bigint, sender: string, recipient: string];
  export interface OutputObject {
    origin: bigint;
    sender: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProcessIdEvent {
  export type InputTuple = [messageId: BytesLike];
  export type OutputTuple = [messageId: string];
  export interface OutputObject {
    messageId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequiredHookSetEvent {
  export type InputTuple = [hook: AddressLike];
  export type OutputTuple = [hook: string];
  export interface OutputObject {
    hook: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Mailbox extends BaseContract {
  connect(runner?: ContractRunner | null): Mailbox;
  waitForDeployment(): Promise<this>;

  interface: MailboxInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PACKAGE_VERSION: TypedContractMethod<[], [string], "view">;

  VERSION: TypedContractMethod<[], [bigint], "view">;

  defaultHook: TypedContractMethod<[], [string], "view">;

  defaultIsm: TypedContractMethod<[], [string], "view">;

  delivered: TypedContractMethod<[_id: BytesLike], [boolean], "view">;

  deployedBlock: TypedContractMethod<[], [bigint], "view">;

  "dispatch(uint32,bytes32,bytes,bytes,address)": TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      metadata: BytesLike,
      hook: AddressLike
    ],
    [string],
    "payable"
  >;

  "dispatch(uint32,bytes32,bytes,bytes)": TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      hookMetadata: BytesLike
    ],
    [string],
    "payable"
  >;

  "dispatch(uint32,bytes32,bytes)": TypedContractMethod<
    [
      _destinationDomain: BigNumberish,
      _recipientAddress: BytesLike,
      _messageBody: BytesLike
    ],
    [string],
    "payable"
  >;

  initialize: TypedContractMethod<
    [
      _owner: AddressLike,
      _defaultIsm: AddressLike,
      _defaultHook: AddressLike,
      _requiredHook: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  latestDispatchedId: TypedContractMethod<[], [string], "view">;

  localDomain: TypedContractMethod<[], [bigint], "view">;

  nonce: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  process: TypedContractMethod<
    [_metadata: BytesLike, _message: BytesLike],
    [void],
    "payable"
  >;

  processedAt: TypedContractMethod<[_id: BytesLike], [bigint], "view">;

  processor: TypedContractMethod<[_id: BytesLike], [string], "view">;

  "quoteDispatch(uint32,bytes32,bytes,bytes,address)": TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      metadata: BytesLike,
      hook: AddressLike
    ],
    [bigint],
    "view"
  >;

  "quoteDispatch(uint32,bytes32,bytes)": TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike
    ],
    [bigint],
    "view"
  >;

  "quoteDispatch(uint32,bytes32,bytes,bytes)": TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      defaultHookMetadata: BytesLike
    ],
    [bigint],
    "view"
  >;

  recipientIsm: TypedContractMethod<
    [_recipient: AddressLike],
    [string],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requiredHook: TypedContractMethod<[], [string], "view">;

  setDefaultHook: TypedContractMethod<
    [_hook: AddressLike],
    [void],
    "nonpayable"
  >;

  setDefaultIsm: TypedContractMethod<
    [_module: AddressLike],
    [void],
    "nonpayable"
  >;

  setRequiredHook: TypedContractMethod<
    [_hook: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PACKAGE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "defaultHook"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "defaultIsm"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "delivered"
  ): TypedContractMethod<[_id: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deployedBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dispatch(uint32,bytes32,bytes,bytes,address)"
  ): TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      metadata: BytesLike,
      hook: AddressLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "dispatch(uint32,bytes32,bytes,bytes)"
  ): TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      hookMetadata: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "dispatch(uint32,bytes32,bytes)"
  ): TypedContractMethod<
    [
      _destinationDomain: BigNumberish,
      _recipientAddress: BytesLike,
      _messageBody: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _owner: AddressLike,
      _defaultIsm: AddressLike,
      _defaultHook: AddressLike,
      _requiredHook: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "latestDispatchedId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "localDomain"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "process"
  ): TypedContractMethod<
    [_metadata: BytesLike, _message: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "processedAt"
  ): TypedContractMethod<[_id: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "processor"
  ): TypedContractMethod<[_id: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "quoteDispatch(uint32,bytes32,bytes,bytes,address)"
  ): TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      metadata: BytesLike,
      hook: AddressLike
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "quoteDispatch(uint32,bytes32,bytes)"
  ): TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "quoteDispatch(uint32,bytes32,bytes,bytes)"
  ): TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      defaultHookMetadata: BytesLike
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "recipientIsm"
  ): TypedContractMethod<[_recipient: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requiredHook"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setDefaultHook"
  ): TypedContractMethod<[_hook: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultIsm"
  ): TypedContractMethod<[_module: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRequiredHook"
  ): TypedContractMethod<[_hook: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DefaultHookSet"
  ): TypedContractEvent<
    DefaultHookSetEvent.InputTuple,
    DefaultHookSetEvent.OutputTuple,
    DefaultHookSetEvent.OutputObject
  >;
  getEvent(
    key: "DefaultIsmSet"
  ): TypedContractEvent<
    DefaultIsmSetEvent.InputTuple,
    DefaultIsmSetEvent.OutputTuple,
    DefaultIsmSetEvent.OutputObject
  >;
  getEvent(
    key: "Dispatch"
  ): TypedContractEvent<
    DispatchEvent.InputTuple,
    DispatchEvent.OutputTuple,
    DispatchEvent.OutputObject
  >;
  getEvent(
    key: "DispatchId"
  ): TypedContractEvent<
    DispatchIdEvent.InputTuple,
    DispatchIdEvent.OutputTuple,
    DispatchIdEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Process"
  ): TypedContractEvent<
    ProcessEvent.InputTuple,
    ProcessEvent.OutputTuple,
    ProcessEvent.OutputObject
  >;
  getEvent(
    key: "ProcessId"
  ): TypedContractEvent<
    ProcessIdEvent.InputTuple,
    ProcessIdEvent.OutputTuple,
    ProcessIdEvent.OutputObject
  >;
  getEvent(
    key: "RequiredHookSet"
  ): TypedContractEvent<
    RequiredHookSetEvent.InputTuple,
    RequiredHookSetEvent.OutputTuple,
    RequiredHookSetEvent.OutputObject
  >;

  filters: {
    "DefaultHookSet(address)": TypedContractEvent<
      DefaultHookSetEvent.InputTuple,
      DefaultHookSetEvent.OutputTuple,
      DefaultHookSetEvent.OutputObject
    >;
    DefaultHookSet: TypedContractEvent<
      DefaultHookSetEvent.InputTuple,
      DefaultHookSetEvent.OutputTuple,
      DefaultHookSetEvent.OutputObject
    >;

    "DefaultIsmSet(address)": TypedContractEvent<
      DefaultIsmSetEvent.InputTuple,
      DefaultIsmSetEvent.OutputTuple,
      DefaultIsmSetEvent.OutputObject
    >;
    DefaultIsmSet: TypedContractEvent<
      DefaultIsmSetEvent.InputTuple,
      DefaultIsmSetEvent.OutputTuple,
      DefaultIsmSetEvent.OutputObject
    >;

    "Dispatch(address,uint32,bytes32,bytes)": TypedContractEvent<
      DispatchEvent.InputTuple,
      DispatchEvent.OutputTuple,
      DispatchEvent.OutputObject
    >;
    Dispatch: TypedContractEvent<
      DispatchEvent.InputTuple,
      DispatchEvent.OutputTuple,
      DispatchEvent.OutputObject
    >;

    "DispatchId(bytes32)": TypedContractEvent<
      DispatchIdEvent.InputTuple,
      DispatchIdEvent.OutputTuple,
      DispatchIdEvent.OutputObject
    >;
    DispatchId: TypedContractEvent<
      DispatchIdEvent.InputTuple,
      DispatchIdEvent.OutputTuple,
      DispatchIdEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Process(uint32,bytes32,address)": TypedContractEvent<
      ProcessEvent.InputTuple,
      ProcessEvent.OutputTuple,
      ProcessEvent.OutputObject
    >;
    Process: TypedContractEvent<
      ProcessEvent.InputTuple,
      ProcessEvent.OutputTuple,
      ProcessEvent.OutputObject
    >;

    "ProcessId(bytes32)": TypedContractEvent<
      ProcessIdEvent.InputTuple,
      ProcessIdEvent.OutputTuple,
      ProcessIdEvent.OutputObject
    >;
    ProcessId: TypedContractEvent<
      ProcessIdEvent.InputTuple,
      ProcessIdEvent.OutputTuple,
      ProcessIdEvent.OutputObject
    >;

    "RequiredHookSet(address)": TypedContractEvent<
      RequiredHookSetEvent.InputTuple,
      RequiredHookSetEvent.OutputTuple,
      RequiredHookSetEvent.OutputObject
    >;
    RequiredHookSet: TypedContractEvent<
      RequiredHookSetEvent.InputTuple,
      RequiredHookSetEvent.OutputTuple,
      RequiredHookSetEvent.OutputObject
    >;
  };
}
