/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "MailboxClient",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MailboxClient__factory>;
    getContractFactory(
      name: "Router",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Router__factory>;
    getContractFactory(
      name: "IPostDispatchHook",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPostDispatchHook__factory>;
    getContractFactory(
      name: "IInterchainSecurityModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IInterchainSecurityModule__factory>;
    getContractFactory(
      name: "ISpecifiesInterchainSecurityModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISpecifiesInterchainSecurityModule__factory>;
    getContractFactory(
      name: "IMailbox",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMailbox__factory>;
    getContractFactory(
      name: "IMessageRecipient",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMessageRecipient__factory>;
    getContractFactory(
      name: "Indexed",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Indexed__factory>;
    getContractFactory(
      name: "Mailbox",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Mailbox__factory>;
    getContractFactory(
      name: "PackageVersioned",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PackageVersioned__factory>;
    getContractFactory(
      name: "Versioned",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Versioned__factory>;
    getContractFactory(
      name: "OwnableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnableUpgradeable__factory>;
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "ContextUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ContextUpgradeable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "PrivateTransferIngress",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateTransferIngress__factory>;
    getContractFactory(
      name: "PrivateTransferVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PrivateTransferVault__factory>;
    getContractFactory(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC20__factory>;
    getContractFactory(
      name: "MockMailbox",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockMailbox__factory>;
    getContractFactory(
      name: "TrustedRelayerIsm",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TrustedRelayerIsm__factory>;

    getContractAt(
      name: "MailboxClient",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MailboxClient>;
    getContractAt(
      name: "Router",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Router>;
    getContractAt(
      name: "IPostDispatchHook",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPostDispatchHook>;
    getContractAt(
      name: "IInterchainSecurityModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IInterchainSecurityModule>;
    getContractAt(
      name: "ISpecifiesInterchainSecurityModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISpecifiesInterchainSecurityModule>;
    getContractAt(
      name: "IMailbox",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMailbox>;
    getContractAt(
      name: "IMessageRecipient",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMessageRecipient>;
    getContractAt(
      name: "Indexed",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Indexed>;
    getContractAt(
      name: "Mailbox",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Mailbox>;
    getContractAt(
      name: "PackageVersioned",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PackageVersioned>;
    getContractAt(
      name: "Versioned",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Versioned>;
    getContractAt(
      name: "OwnableUpgradeable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnableUpgradeable>;
    getContractAt(
      name: "Initializable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "ContextUpgradeable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ContextUpgradeable>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20Permit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "PrivateTransferIngress",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateTransferIngress>;
    getContractAt(
      name: "PrivateTransferVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PrivateTransferVault>;
    getContractAt(
      name: "MockERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC20>;
    getContractAt(
      name: "MockMailbox",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockMailbox>;
    getContractAt(
      name: "TrustedRelayerIsm",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TrustedRelayerIsm>;

    deployContract(
      name: "MailboxClient",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MailboxClient>;
    deployContract(
      name: "Router",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Router>;
    deployContract(
      name: "IPostDispatchHook",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPostDispatchHook>;
    deployContract(
      name: "IInterchainSecurityModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInterchainSecurityModule>;
    deployContract(
      name: "ISpecifiesInterchainSecurityModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISpecifiesInterchainSecurityModule>;
    deployContract(
      name: "IMailbox",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMailbox>;
    deployContract(
      name: "IMessageRecipient",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMessageRecipient>;
    deployContract(
      name: "Indexed",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Indexed>;
    deployContract(
      name: "Mailbox",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Mailbox>;
    deployContract(
      name: "PackageVersioned",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PackageVersioned>;
    deployContract(
      name: "Versioned",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Versioned>;
    deployContract(
      name: "OwnableUpgradeable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OwnableUpgradeable>;
    deployContract(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "ContextUpgradeable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ContextUpgradeable>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "PrivateTransferIngress",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateTransferIngress>;
    deployContract(
      name: "PrivateTransferVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateTransferVault>;
    deployContract(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "MockMailbox",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockMailbox>;
    deployContract(
      name: "TrustedRelayerIsm",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrustedRelayerIsm>;

    deployContract(
      name: "MailboxClient",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MailboxClient>;
    deployContract(
      name: "Router",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Router>;
    deployContract(
      name: "IPostDispatchHook",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPostDispatchHook>;
    deployContract(
      name: "IInterchainSecurityModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInterchainSecurityModule>;
    deployContract(
      name: "ISpecifiesInterchainSecurityModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISpecifiesInterchainSecurityModule>;
    deployContract(
      name: "IMailbox",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMailbox>;
    deployContract(
      name: "IMessageRecipient",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMessageRecipient>;
    deployContract(
      name: "Indexed",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Indexed>;
    deployContract(
      name: "Mailbox",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Mailbox>;
    deployContract(
      name: "PackageVersioned",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PackageVersioned>;
    deployContract(
      name: "Versioned",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Versioned>;
    deployContract(
      name: "OwnableUpgradeable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OwnableUpgradeable>;
    deployContract(
      name: "Initializable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "ContextUpgradeable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ContextUpgradeable>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20Permit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "PrivateTransferIngress",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateTransferIngress>;
    deployContract(
      name: "PrivateTransferVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PrivateTransferVault>;
    deployContract(
      name: "MockERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "MockMailbox",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockMailbox>;
    deployContract(
      name: "TrustedRelayerIsm",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrustedRelayerIsm>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
