/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockMailbox__factory } from "./MockMailbox__factory";
export { TestToken__factory } from "./TestToken__factory";
