/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockMailboxInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "dispatch"
      | "latestMessageId"
      | "messageIds"
      | "processor"
      | "processorAddress"
      | "setProcessor"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Dispatched"): EventFragment;

  encodeFunctionData(
    functionFragment: "dispatch",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "latestMessageId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "messageIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processorAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setProcessor",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "dispatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latestMessageId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "messageIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "processor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProcessor",
    data: BytesLike
  ): Result;
}

export namespace DispatchedEvent {
  export type InputTuple = [
    destinationDomain: BigNumberish,
    recipient: BytesLike,
    message: BytesLike,
    messageId: BytesLike
  ];
  export type OutputTuple = [
    destinationDomain: bigint,
    recipient: string,
    message: string,
    messageId: string
  ];
  export interface OutputObject {
    destinationDomain: bigint;
    recipient: string;
    message: string;
    messageId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockMailbox extends BaseContract {
  connect(runner?: ContractRunner | null): MockMailbox;
  waitForDeployment(): Promise<this>;

  interface: MockMailboxInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  dispatch: TypedContractMethod<
    [
      _destinationDomain: BigNumberish,
      _recipient: BytesLike,
      _message: BytesLike
    ],
    [string],
    "payable"
  >;

  latestMessageId: TypedContractMethod<[], [string], "view">;

  messageIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  processor: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  processorAddress: TypedContractMethod<[], [string], "view">;

  setProcessor: TypedContractMethod<
    [_processor: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "dispatch"
  ): TypedContractMethod<
    [
      _destinationDomain: BigNumberish,
      _recipient: BytesLike,
      _message: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "latestMessageId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "messageIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "processor"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "processorAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setProcessor"
  ): TypedContractMethod<[_processor: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Dispatched"
  ): TypedContractEvent<
    DispatchedEvent.InputTuple,
    DispatchedEvent.OutputTuple,
    DispatchedEvent.OutputObject
  >;

  filters: {
    "Dispatched(uint32,bytes32,bytes,bytes32)": TypedContractEvent<
      DispatchedEvent.InputTuple,
      DispatchedEvent.OutputTuple,
      DispatchedEvent.OutputObject
    >;
    Dispatched: TypedContractEvent<
      DispatchedEvent.InputTuple,
      DispatchedEvent.OutputTuple,
      DispatchedEvent.OutputObject
    >;
  };
}
